# Generated by Django 3.2.5 on 2021-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
